openapi: 3.0.1
info:
  title: Authentication API
  description: API endpoints for user authentication using Better Auth
  version: 1.0.0
paths:
  /api/auth/signin:
    post:
      summary: Authenticate user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  minLength: 8
                  description: User's password
                rememberMe:
                  type: boolean
                  description: Whether to create a persistent session
              required:
                - email
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Invalid input or credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
  /api/auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                  description: User's display name
                email:
                  type: string
                  format: email
                  description: User's email address
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                  pattern: "^[a-zA-Z0-9_-]+$"
                  description: User's unique username
                password:
                  type: string
                  minLength: 8
                  description: User's password with at least one uppercase, lowercase, number, and special character
              required:
                - name
                - email
                - username
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Invalid input or duplicate email/username
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
  /api/auth/session:
    get:
      summary: Get current user session
      responses:
        '200':
          description: Current session data
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: No active session
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
  /api/auth/signout:
    post:
      summary: Sign out current user
      responses:
        '200':
          description: Successfully signed out
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: No active session
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        name:
          type: string
          description: User's display name
        email:
          type: string
          format: email
          description: User's email address
        username:
          type: string
          description: User's unique username
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
        lastLoginAt:
          type: string
          format: date-time
          description: Last login timestamp
    Session:
      type: object
      properties:
        sessionId:
          type: string
          description: Unique session identifier
        userId:
          type: string
          description: Reference to user.id
        expiresAt:
          type: string
          format: date-time
          description: Session expiration timestamp
        createdAt:
          type: string
          format: date-time
          description: Session creation timestamp
        isPersistent:
          type: boolean
          description: Whether this is a persistent session ("Remember me")